### ISSUE TITLE
Proxy settings defaulting to port 3128 [Bug]

### ISSUE THREAD

**Issue by stacsirt** [StrangeBeeCorp/TheHive-feedback#11]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian |
| Virtualized  Env.          | True |
| TheHive version            | 5.0.10-1 |
| Package Type               | DEB |
| Database                   | Cassandra |
| Index type                 | Elasticsearch |

### Problem Description
Hi,

We run our proxy on a different port to 3128 (which appears to be a default setting within thehive5 that we cannot change). When we provide our proxy along with its port inside the config for Cortex or MISP in the new UI, it appears to be adding ':3128' on the end of the string (according to the logs) which is therefore causing it not to connect. We've tried multiple variations of this but it still persists to add the port 3128. This was not an issue in previous versions. 

Is anyone else experiencing the same issue? We can't seem find any workaround for this (not identified anywhere that allows us to change that default port).

Log file screenshots can be provided if necessary.

Thanks.

### Steps to Reproduce
1. In TheHive5 UI, navigate to the config settings for Cortex or MISP.
2. Fill in the necessary fields and enter proxy settings.
3. Look at the logs and it should default your proxy to port 3128.

**Comment by vdebergue** [comment]
Hello,

We confirmed the issue on our side, the input for the port setting is missing in the page.
A workaround would be to make the request in the browser for MISP or Cortex. Then take the request with the browser tools and replay it while manually adding the `port` setting in the proxy section.

We'll try to fix this in our next release which will be released very soon.

**Comment by vdebergue** [comment]
A fix was released for this in version 5.0.12
