### ISSUE TITLE
[Bug] Problem when merginc case by title

### ISSUE THREAD

**Issue by FormindAPE** [StrangeBeeCorp/TheHive-feedback#15]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu   |
| OS version (client)        | Windows 11       |
| Virtualized  Env.          | True                           |
| Dedicated RAM              | 4 GB                                 |
| vCPU                       | 2                       |
| TheHive version            | 5.0.14-1                               |
| Package Type               |  Docker |
| Database                   | Cassandra              |
| Index type                 | Elasticsearch               |
| Attachments storage        |  S3                 |
| Browser type & version     |  firefox 105.0.1                   |

### Problem Description
when merging an alert to an existing case and using the title search. when selecting the case you want to merge to, if multiple case have the same title, even if you select the latest ID it will select the case with the lowsest ID.

### Steps to Reproduce
1. create multiple case with the same title 
2. close all case except the last one (the highest id) that is in "In progress" stage
3. get one alert you want to join to that case
4. clic on merge 
5. search by title, enter the title of the case
6. select the last ID available (the highest id)
7. the one with lowsest id is selected

### Complementary information
before clicking case 152:
![image](https://user-images.githubusercontent.com/100144503/192472349-5b7c2263-7cbd-4ace-8fcd-f48725d202df.png)

after clicking on case 152:
![image](https://user-images.githubusercontent.com/100144503/192472758-19c58d4e-7ab1-4c75-9b25-41099a58b90e.png)

the same thing append if I clic on other case greater than 9 (it always select the case 9)

**Comment by mayday-sama** [comment]
Hello @FormindAPE !

This bug should have been fixed in the latest release, TheHive 5.0.17.

Thanks for your feedback !
