### ISSUE TITLE
[Bug] Impossible to scrole on right in Case and Alert view

### ISSUE THREAD

**Issue by t-paris** [StrangeBeeCorp/TheHive-feedback#3]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| TheHive version            | 5.0.6.1                                 |
| Package Type               |  Docker                               |
| Database                   | Cassandra                 |
| Index type                 | Elasticsearch                           |
| Attachments storage        |  S3                  |
| Browser type & version     | If applicable                         |

### Problem Description
When there is a large  Customfield / Tag, you can't reduce the "Title" Field in order to see the collums on the right unless you scroll all the way down the list of alert/case.

### Steps to Reproduce
1. Create an alert /  case with a large tags like "https://github.com/StrangeBeeCorp/TheHive-feedback/issues/new?assignees=&labels=bug%2C+TheHive&template=bug_report.md&title=%5BBug%5D"
2. Go to yourthehive.com/alerts or yourthehive.com/case 

### Possible Solutions
1. Make the scrolling capability even when you are not at the end of the page
2. Being able to size the top bar according to our need

**Comment by nadouani** [comment]
Hello @tpa-cyb this has been scheduled for 5.0.7. Thanks for your feedback.

**Comment by jamet-julien** [comment]
hello @tpa-cyb the 5.0.7 is available.
